Vagrant.configure(2) do |config|
  config.vm.define "dev1" do |dev|
    dev.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "../vagrant-ubuntu/Vagrantfile"
      d.build_dir = "."
      d.name = "dev1"
    end
    dev.ssh.username = "docker"
  end

  config.vm.define "dev2" do |dev|
    dev.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "../vagrant-ubuntu/Vagrantfile"
      d.build_dir = "."
      d.name = "dev2"
      d.link("dev1:dev1")
    end
    dev.ssh.username = "docker"
  end
end
